INSERT INTO [dbo].[PulseStocks] (pulse_stock_size, pulse_name) VALUES (1000, 'Chickpea')
INSERT INTO [dbo].[PulseStocks] (pulse_stock_size, pulse_name) VALUES (1000, 'Lentil')
INSERT INTO [dbo].[PulseStocks] (pulse_stock_size, pulse_name) VALUES (1000, 'Haricot Bean')
INSERT INTO [dbo].[PulseStocks] (pulse_stock_size, pulse_name) VALUES (1000, 'Pea')
INSERT INTO [dbo].[PulseStocks] (pulse_stock_size, pulse_name) VALUES (1000, 'Rice')